# Generated by Django 4.2.18 on 2025-01-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('date', models.IntegerField(max_length=100)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField(max_length=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=6)),
            ],
        ),
    ]
