# Generated by Django 4.2.18 on 2025-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='male', max_length=6),
        ),
    ]
