# Generated by Django 4.2.18 on 2025-01-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_reg_date_alter_reg_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='date',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
