# Generated by Django 4.2.18 on 2025-01-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_rename_date_reg_dob_rename_phone_reg_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
    ]
