# Generated by Django 4.2.18 on 2025-01-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_alter_reg_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('jobDescription', models.CharField(max_length=200)),
                ('jobResponsibilities', models.CharField(max_length=500)),
                ('jobQualifications', models.CharField(max_length=200)),
                ('salaryRange', models.CharField(max_length=100)),
                ('contactEmail', models.EmailField(max_length=20, unique=True)),
                ('applicationDeadline', models.DateField()),
                ('companyName', models.CharField(max_length=50)),
                ('companyAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
