# Generated by Django 4.2.18 on 2025-02-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=150)),
                ('contactPerson', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=400)),
                ('confirmPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
