# Generated by Django 4.2.18 on 2025-02-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0007_job_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
