# Generated by Django 4.2.18 on 2025-02-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_rename_comment_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='subscribe',
        ),
    ]
