# Generated by Django 4.2.18 on 2025-02-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0010_remove_feedback_feedback_type_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
