# Generated by Django 4.2.18 on 2025-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0012_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('Inactive', 'inactive')], default='pending', max_length=20, null=True),
        ),
    ]
