# Generated by Django 4.2.18 on 2025-03-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0013_reg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='sstatus',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('Inactive', 'inactive')], default='pending', max_length=20, null=True),
        ),
    ]
