# Generated by Django 4.2.18 on 2025-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0014_reg_sstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pprofile/'),
        ),
    ]
