# Generated by Django 4.2.18 on 2025-03-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0017_certificate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('job_title_1', models.CharField(max_length=255)),
                ('company_1', models.CharField(max_length=255)),
                ('dates_1', models.CharField(max_length=255)),
                ('responsibilities_1', models.TextField()),
                ('job_title_2', models.CharField(blank=True, max_length=255, null=True)),
                ('company_2', models.CharField(blank=True, max_length=255, null=True)),
                ('dates_2', models.CharField(blank=True, max_length=255, null=True)),
                ('responsibilities_2', models.TextField(blank=True, null=True)),
                ('degree', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('graduation_date', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('references', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
