# Generated by Django 4.2.18 on 2025-03-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0018_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dates_1',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dates_2',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='graduation_date',
            field=models.DateField(max_length=255),
        ),
    ]
