# Generated by Django 4.2.18 on 2025-03-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0019_alter_resume_dates_1_alter_resume_dates_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_title_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
