# Generated by Django 4.2.18 on 2025-03-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0021_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='company_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
