# Generated by Django 4.2.18 on 2025-03-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0022_alter_resume_company_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dates_1',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
