# Generated by Django 5.0.1 on 2025-04-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0028_alter_addjob_id_alter_certificate_id_alter_exam_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_date', models.DateField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='resume_app.addjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='resume_app.reg')),
            ],
        ),
    ]
